name: PortOpt
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - bs4=4.9.3
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.6
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - icc_rt=2019.0.0
  - idna=2.10
  - importlib-metadata=3.7.3
  - intel-openmp=2020.3
  - ipykernel=5.5.0
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - msys2-conda-epoch=20160418
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - notebook=6.3.0
  - numpy=1.20.1
  - openssl=1.1.1j
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.1
  - pickleshare=0.7.5
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.18
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=300
  - pywinpty=0.5.7
  - pyzmq=22.0.3
  - requests=2.25.1
  - scipy=1.6.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - six=1.15.0
  - sniffio=1.2.0
  - soupsieve=2.0.1
  - sqlite=3.35.2
  - terminado=0.9.3
  - testpath=0.4.4
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.4
  - zipp=3.4.1
  - pip:
    - lxml==4.6.3
    - multitasking==0.0.9
    - yfinance==0.1.55
